version: '3.7'

services:
  database_carsS: 
    image: postgres
    container_name: database_carsS
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: 'carsS'
    ports:
      - 4001:4001
    volumes:
      - .:/usr/app
    links:
      - database_carsS
    depends_on: 
      - database_carsS

volumes:
  pgdata:
    driver: local